version: 1

formatters:
    simple:
        format: "[%(levelname)s] %(funcName)s (%(lineno)d): %(message)s"

    verbose:
        format: "[%(asctime)s] %(levelname)s [%(filename)s %(name)s %(funcName)s (%(lineno)d)]: %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: verbose
        filename : debug.log

loggers:
    root:
        level: DEBUG
        handlers: [console,file]
        propagate: yes

    # __main__:   
    #     level: DEBUG
    #     handlers: [console, file]
    #     propagate: yes